version: "2.0"

services:

  db:
    image: mysql:5.7.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql/ # ./mysql路径可以替换成自己的路径
      - ../../sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sf-admin
      MYSQL_USER: sf-admin
      MYSQL_PASSWORD: 123456

  redis:
    image: redis:alpine
    command: --requirepass "123456"
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai

  sfserver:
    image: qa894178522/sfnestadmin:stable
    restart: always
    depends_on:
      - db
      - redis
    environment:
      MYSQL_HOST: '175.178.67.107'
      MYSQL_PORT: 3396
      MYSQL_USERNAME: 'wwqroot'
      MYSQL_PASSWORD: 'wwqroot'
      MYSQL_DATABASE: next_admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      # 可选
      MAILER_HOST: xxx
      MAILER_PORT: xxx
      MAILER_USER: xxx
      MAILER_PASS: xxx
      AMAP_KEY: xxx
      QINIU_ACCESSKEY: '6Euae44_vJP177085yjMt_KSDq0rQ6D6bH5zk7jI'
      QINIU_SECRETKEY: 'lzkm5EZHshjko7DoL4rKREEoWKTB0loozxEr4DTc'
      QINIU_DOMAIN: http://rjslvjju0.hn-bkt.clouddn.com
      QINIU_BUCKET: harleen
      QINIU_ZONE: xxx # Zone_as0 | Zone_na0 | Zone_z0 | Zone_z1 | Zone_z2
      QINIU_ACCESS_TYPE: public # or private

  sfvue:
    image: qa894178522/sfvueadmin:nest
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - sfserver
    ports:
      - 7002:80
